version: '3.8'

services:
  backend:
    build: ./Lk_Advertisement_backend
    container_name: lk_ads_backend
    ports:
      - "8080:8080"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://host.docker.internal:3306/lk_ads_db?useSSL=false&serverTimezone=UTC
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=password
    restart: always

  frontend:
    build: ./Lk_Advertisement_frontend
    container_name: lk_ads_frontend
    ports:
      - "5173:80"
    restart: always
